export const FETCH_PRODUCTS_BEGIN   = 'FETCH_PRODUCTS_BEGIN';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const FETCH_TYPE = 'FETCH_TYPE';
export const SEARCH_ITEM = 'SEARCH_ITEM';
export const SET_CHANGE_COLOR= "SET_CHANGE_COLOR"